build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4
      tests:
        override:
          - php-scrutinizer-run

filter:
  paths:
    - 'app/*'

checks:
  php: true
