build:
  nodes:
    analysis:
      services:
        mariadb: 10
      environment:
        variables:
          DB_DATABASE: 'scrutinizer'
          DB_USERNAME: 'root'
          DB_PASSWORD: ''
        php:
          version: 7.3
      project_setup:
        override:
          - 'true'
      tests:
        before:
          - command: mysql -u root -e "CREATE DATABASE scrutinizer;"
          - command: php artisan migrate
        override:
          - command: ./src/vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover
          - php-scrutinizer-run

filter:
  paths:
    - 'src/app/*'
  excluded_paths:
    - 'src/app/views/*'
    - 'src/app/config/*'
    - 'src/app/database/*'
checks:
  php: true
