version: "3"

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - default

  db:
    image: mariadb:latest
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: application
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - 4444:8080
    networks:
      - default

  app:
    build:

      # Alpine / Nginx / PHP-FPM 8.1
      context: ./
      dockerfile: .docker/php8.1-fpm-alpine/Dockerfile

        # Ubuntu / Apache / PHP 8.0
        #      context: .docker/php8.0-apache/
        # (don't forget the volume)
      args:
        user: king
        uid: 1000
        development: "true"
    restart: always
    container_name: app
    depends_on:
      - db
      - redis
    ports:
      - 80:80
    environment:
      - PORT=80
    volumes:
      - ./:/var/www/
    #      - ./.docker/php8.0-apache/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - default

volumes:
  web-app:
    driver: local
  mysql-data:
    driver: local

networks:
  default:
